# Generated by Django 5.0.4 on 2025-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
