# Generated by Django 5.0.4 on 2025-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_guest_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
