# Generated by Django 5.0.4 on 2025-02-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_history_id_alter_guest_history_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
