# Generated by Django 5.0.4 on 2025-02-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_guest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='history_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
