# Generated by Django 5.0.4 on 2025-02-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_guest_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
