# Generated by Django 5.0.4 on 2025-02-15 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('download_total', models.PositiveIntegerField(default=0)),
                ('history_total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filesystem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.departmentlist'),
        ),
    ]
