# Generated by Django 5.0.4 on 2025-02-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='employees_id',
        ),
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.DeleteModel(
            name='FileSystem',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
