from django.contrib import admin
from .admin_register.Departemnt_list import DepartmentListAdmin
from .admin_register.PermissionSetting_admin import PermissionSettingAdmin
from .admin_register.request_admin import RequestAdmin
from .admin_register.fileSystem import FilesytemAdmin