# Generated by Django 5.0.4 on 2025-02-18 16:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsetting',
            name='action',
        ),
        migrations.AddField(
            model_name='permissionsetting',
            name='actions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=20),
        ),
    ]
