# Generated by Django 5.0.4 on 2025-05-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_backup_recovery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'verbose_name': 'Backup and Recovery', 'verbose_name_plural': 'Backup and Recovery'},
        ),
        migrations.RemoveField(
            model_name='backup',
            name='status',
        ),
    ]
