# Generated by Django 5.0.4 on 2025-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_permissionsetting_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesystem',
            name='mirror_file_path',
        ),
        migrations.AddField(
            model_name='filesystem',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filesystem',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permissionsetting',
            name='allowed_filter_fields',
            field=models.TextField(blank=True, help_text='Comma separated list of allowed filter fields (e.g. id, title, author, year,  type, availability, created_at, updated_time, department, approved, original_file_path, file_size, file_extension, uploaded_by)', null=True),
        ),
    ]
