# Generated by Django 5.0.4 on 2025-02-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_filesystem_mirror_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystem',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
