# Generated by Django 5.0.4 on 2025-02-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_filesystem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesystem',
            old_name='type',
            new_name='file_type',
        ),
    ]
