# Generated by Django 5.0.4 on 2025-02-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_rename_type_filesystem_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesystem',
            name='file_type',
        ),
    ]
