# Generated by Django 5.0.4 on 2025-02-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_filesystem_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystem',
            name='disapproval_reason',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
