# Generated by Django 5.0.4 on 2025-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_filesystem_disapproval_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsetting',
            name='allowed_filter_fields',
            field=models.TextField(blank=True, default='id,title,author,year,type,availability,created_at,updated_time,department,approved,original_file_path,file_size,file_extension,uploaded_by,disapproval_reason', help_text='Comma separated list of allowed filter fields (e.g. id, title, author, year,', null=True),
        ),
    ]
