# Generated by Django 5.0.4 on 2025-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_popularsearch_searchquery_remove_filesystem_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularsearch',
            options={'ordering': ['-count', '-last_searched']},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='popularsearch',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
