# Generated by Django 5.0.4 on 2025-02-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('files', '0011_alter_popularsearch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.departmentlist'),
        ),
    ]
